Update readme.md
VuongRon/TsushoBot pull request #47
Opened 2021-05-17 18:22 UTC by DarkStoorM

`npm i` will now automatically build the source and clone the environment file

* applies Markdown lints

🏃‍♂️ 💨

2021-05-18 16:22 UTC, Hofled requested changes
Please refer to [this](https://www.npmjs.com/package/concurrently) as a solution.

2021-05-18 16:22 UTC, Hofled commented on package.json
> +    "postinstall": "npm run db:migrate && npm run build:src && npm run cloneEnv",
Please add `concurrently` to the project, and use that to run multiple npm commands instead of the npm native way. @DarkStoorM

2021-05-19 18:48 UTC, DarkStoorM commented
🎉

2021-05-19 18:50 UTC, dcepil approved these changes
Looking good 🤸

2021-05-20 12:13 UTC, Hofled commented
I don't have access to a computer to confirm that it functions properly on a new environment but it indeed looks good 👍
Feel free to merge it when you can

2021-05-20 12:14 UTC, Hofled approved these changes

2021-08-06 14:10 UTC, merged